<a href="https://colab.research.google.com/github/sadaf-rad/start_ML/blob/main/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.14.0'

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Part 1 - Data Preprocessing

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2 , random_state = 0 )

## Part 2 - Building the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, epochs = 100 , batch_size = 32)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 185186.7500
Epoch 2/100
240/240 [==============================] - 1s 4ms/step - loss: 184980.7344
Epoch 3/100
240/240 [==============================] - 1s 4ms/step - loss: 184775.0000
Epoch 4/100
240/240 [==============================] - 1s 4ms/step - loss: 184569.5000
Epoch 5/100
240/240 [==============================] - 1s 2ms/step - loss: 184363.9531
Epoch 6/100
240/240 [==============================] - 1s 2ms/step - loss: 184158.5156
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 183953.2812
Epoch 8/100
240/240 [==============================] - 1s 2ms/step - loss: 183748.1250
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 183543.0156
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 183338.0781
Epoch 11/100
240/240 [==============================] - 1s 2ms/step - loss: 183133.2500
Epoch 12/100
240/240 [===================

### Predicting the results of the Test set

In [ ]:
y _pred= ann.predict(X_test)
np.set_printoptions(precision=2)
print (np.concatenate((y_pred.reshape(len(y_pred),1) ,y_test.reshape(len(y_test),1)),1))


60/60 [==============================] - 0s 1ms/step
[[ 48.13 431.23]
 [ 48.13 460.01]
 [ 48.13 461.14]
 ...
 [ 48.13 473.26]
 [ 48.13 438.  ]
 [ 48.13 463.28]]
